package com.justindwinata.usahanaik.domain.localization

data class AppStrings(
    val appTagline: String,
    val language: String,
    val continueLocalMode: String,
    val login: String,
    val register: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val ownerName: String,
    val authDemoNote: String,
    val dashboard: String,
    val plan: String,
    val ideas: String,
    val report: String,
    val profile: String,
    val businessSetup: String,
    val completeSetup: String,
    val businessHealth: String,
    val financialSummary: String,
    val weeklyProgress: String,
    val contentPlanner: String,
    val businessReport: String,
    val reminders: String,
    val quickActions: String,
    val monthlyRevenue: String,
    val monthlyExpenses: String,
    val estimatedProfit: String,
    val profitMargin: String,
    val addFinancialEntry: String,
    val generateWeeklyPlan: String,
    val generateContentIdeas: String,
    val openBusinessReport: String,
    val settings: String,
    val demoMode: String,
    val loadDemoData: String,
    val clearDemoData: String,
    val localFirstNote: String,
    val emptyState: String,
    val loading: String,
    val needsAttention: String,
    val nextAction: String,
    val preview: String,
    val businessCommandCenter: String,
    val localDataActive: String,
    val localPlanningGuidance: String,
    val dashboardNoProfileSubtitle: String,
    val dashboardHeroTitle: String,
    val dashboardNoProfileMessage: String,
    val dashboardReadyMessage: String,
    val financialSummarySubtitle: String,
    val quickActionsSubtitle: String,
    val recordedThisMonth: String,
    val incomeMinusExpenses: String,
    val estimatedMargin: String,
    val generatedIdeas: String,
    val savedIdeas: String,
    val contentCalendar: String,
    val localGeneration: String,
    val fallbackUsed: String,
    val save: String,
    val cancel: String,
    val delete: String,
    val continueText: String,
    val noGuaranteedProfit: String
)

object AppCopyProvider {
    fun strings(language: AppLanguage): AppStrings {
        return when (language) {
            AppLanguage.Indonesian -> indonesianStrings
            AppLanguage.English -> englishStrings
        }
    }

    private val indonesianStrings = AppStrings(
        appTagline = "Planner bisnis lokal untuk UMKM yang ingin lebih rapi, terarah, dan konsisten.",
        language = "Bahasa",
        continueLocalMode = "Lanjut mode lokal",
        login = "Masuk",
        register = "Daftar",
        email = "Email",
        password = "Kata sandi",
        confirmPassword = "Konfirmasi kata sandi",
        ownerName = "Nama pemilik",
        authDemoNote = "Autentikasi belum aktif di versi demo lokal ini.",
        dashboard = "Dashboard",
        plan = "Rencana",
        ideas = "Ide",
        report = "Laporan",
        profile = "Profil",
        businessSetup = "Setup Bisnis",
        completeSetup = "Lengkapi setup",
        businessHealth = "Kesehatan Bisnis",
        financialSummary = "Ringkasan Keuangan",
        weeklyProgress = "Progress Mingguan",
        contentPlanner = "Planner Konten",
        businessReport = "Laporan Bisnis",
        reminders = "Pengingat",
        quickActions = "Aksi Cepat",
        monthlyRevenue = "Omzet Bulanan",
        monthlyExpenses = "Pengeluaran Bulanan",
        estimatedProfit = "Estimasi Profit",
        profitMargin = "Margin Profit",
        addFinancialEntry = "Catat keuangan",
        generateWeeklyPlan = "Buat rencana mingguan",
        generateContentIdeas = "Buat ide konten",
        openBusinessReport = "Buka laporan bisnis",
        settings = "Pengaturan",
        demoMode = "Mode Demo",
        loadDemoData = "Muat Data Demo",
        clearDemoData = "Hapus Data Demo",
        localFirstNote = "Data disimpan lokal di perangkat ini.",
        emptyState = "Belum ada data",
        loading = "Memuat",
        needsAttention = "Perlu perhatian",
        nextAction = "Aksi berikutnya",
        preview = "Pratinjau",
        businessCommandCenter = "Pusat kontrol usaha",
        localDataActive = "Data lokal aktif",
        localPlanningGuidance = "Panduan rencana lokal",
        dashboardNoProfileSubtitle = "Lengkapi setup atau muat data demo untuk membuka pusat kontrol usaha.",
        dashboardHeroTitle = "Pantau kondisi usaha, rencana mingguan, konten, laporan, pengingat, dan progress dari data lokal.",
        dashboardNoProfileMessage = "Lengkapi setup atau muat data demo dari Profil untuk mencoba pengalaman portfolio penuh.",
        dashboardReadyMessage = "Dashboard ini membantu monitoring dan perencanaan. Tidak ada klaim profit pasti.",
        financialSummarySubtitle = "KPI utama dari catatan lokal dan baseline setup.",
        quickActionsSubtitle = "Mulai dari aksi yang paling sesuai dengan pekerjaan hari ini.",
        recordedThisMonth = "Tercatat bulan ini",
        incomeMinusExpenses = "Pemasukan dikurangi pengeluaran",
        estimatedMargin = "Margin estimasi",
        generatedIdeas = "Ide yang dibuat",
        savedIdeas = "Ide tersimpan",
        contentCalendar = "Kalender konten",
        localGeneration = "Generator lokal",
        fallbackUsed = "Fallback lokal",
        save = "Simpan",
        cancel = "Batal",
        delete = "Hapus",
        continueText = "Lanjut",
        noGuaranteedProfit = "UsahaNaik tidak menjamin kenaikan profit dan bukan nasihat keuangan profesional."
    )

    private val englishStrings = AppStrings(
        appTagline = "A local-first business planner for UMKM owners who want clearer, more consistent execution.",
        language = "Language",
        continueLocalMode = "Continue in local mode",
        login = "Login",
        register = "Register",
        email = "Email",
        password = "Password",
        confirmPassword = "Confirm password",
        ownerName = "Owner name",
        authDemoNote = "Authentication is not enabled in this local demo version.",
        dashboard = "Dashboard",
        plan = "Plan",
        ideas = "Ideas",
        report = "Report",
        profile = "Profile",
        businessSetup = "Business Setup",
        completeSetup = "Complete setup",
        businessHealth = "Business Health",
        financialSummary = "Financial Summary",
        weeklyProgress = "Weekly Progress",
        contentPlanner = "Content Planner",
        businessReport = "Business Report",
        reminders = "Reminders",
        quickActions = "Quick Actions",
        monthlyRevenue = "Monthly Revenue",
        monthlyExpenses = "Monthly Expenses",
        estimatedProfit = "Estimated Profit",
        profitMargin = "Profit Margin",
        addFinancialEntry = "Add financial entry",
        generateWeeklyPlan = "Generate weekly plan",
        generateContentIdeas = "Generate content ideas",
        openBusinessReport = "Open business report",
        settings = "Settings",
        demoMode = "Demo Mode",
        loadDemoData = "Load Demo Data",
        clearDemoData = "Clear Demo Data",
        localFirstNote = "Data is stored locally on this device.",
        emptyState = "No data yet",
        loading = "Loading",
        needsAttention = "Needs attention",
        nextAction = "Next action",
        preview = "Preview",
        businessCommandCenter = "Business command center",
        localDataActive = "Local data active",
        localPlanningGuidance = "Local planning guidance",
        dashboardNoProfileSubtitle = "Complete setup or load demo data to open the business command center.",
        dashboardHeroTitle = "Monitor business health, weekly plans, content, reports, reminders, and progress from local data.",
        dashboardNoProfileMessage = "Complete setup or load demo data from Profile to explore the full portfolio experience.",
        dashboardReadyMessage = "This dashboard supports monitoring and planning. It does not promise guaranteed profit.",
        financialSummarySubtitle = "Key KPIs from local records and setup baseline.",
        quickActionsSubtitle = "Start from the action that best matches today's work.",
        recordedThisMonth = "Recorded this month",
        incomeMinusExpenses = "Income minus expenses",
        estimatedMargin = "Estimated margin",
        generatedIdeas = "Generated Ideas",
        savedIdeas = "Saved Ideas",
        contentCalendar = "Content Calendar",
        localGeneration = "Local generator",
        fallbackUsed = "Local fallback",
        save = "Save",
        cancel = "Cancel",
        delete = "Delete",
        continueText = "Continue",
        noGuaranteedProfit = "UsahaNaik does not guarantee profit increase and is not professional financial advice."
    )
}
