#!/usr/bin/env python3
"""Build a clean visual-only package for portfolio and LinkedIn assets."""

from __future__ import annotations

import hashlib
import os
import shutil
import subprocess
import zipfile
from datetime import datetime, timezone
from pathlib import Path


FORBIDDEN_NAMES = {
    ".git",
    ".gradle",
    ".idea",
    ".venv",
    "__pycache__",
    "build",
    "node_modules",
    "venv",
}

FORBIDDEN_SUFFIXES = {
    ".7z",
    ".aab",
    ".apk",
    ".bin",
    ".ckpt",
    ".gguf",
    ".h5",
    ".jar",
    ".keras",
    ".onnx",
    ".pt",
    ".pth",
    ".rar",
    ".safetensors",
    ".tar",
    ".zip",
}

SCREENSHOT_DIR = Path("docs/evidence/screenshots/final")
MOCKUP_DIR = Path("docs/visuals/mockups")
LINKEDIN_DIR = Path("docs/visuals/linkedin_campaign")


def run_git(args: list[str], fallback: str = "unknown") -> str:
    try:
        return subprocess.check_output(["git", *args], text=True).strip() or fallback
    except (subprocess.CalledProcessError, FileNotFoundError):
        return fallback


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def is_forbidden(path: Path) -> bool:
    parts = set(path.parts)
    if parts.intersection(FORBIDDEN_NAMES):
        return True
    return path.suffix.lower() in FORBIDDEN_SUFFIXES


def copy_tree_contents(project_dir: Path, source: Path, destination: Path) -> list[str]:
    included: list[str] = []
    source_path = project_dir / source
    if not source_path.exists():
        return included

    for item in sorted(source_path.rglob("*")):
        if item.is_dir() or is_forbidden(item.relative_to(project_dir)):
            continue
        relative_inside_source = item.relative_to(source_path)
        target = destination / relative_inside_source
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
        included.append(str(target.relative_to(destination.parents[0])))
    return included


def build_readme(project_name: str, app_was_run: str) -> str:
    return f"""# {project_name} Visual Package

This package contains presentation assets for portfolio and LinkedIn use.

## Contents

- `screenshots/` - runtime screenshot folder or capture guide.
- `mockups/` - portfolio mockups generated from the project scope and visual direction.
- `linkedin_campaign/` - LinkedIn cover, square post, carousel, and banner visuals.
- `VISUAL_PACKAGE_MANIFEST.md` - package metadata and included file list.

## Screenshot Source

{app_was_run}

## Usage

Use `linkedin_cover.png` for a wide LinkedIn post, `linkedin_square_post.png` for a compact project highlight, and the carousel files for a multi-slide project story.

These visuals describe implemented local-first portfolio functionality only. They do not claim real backend authentication, cloud sync, paid AI API usage, guaranteed business outcomes, or professional financial advice.
"""


def build_manifest(
    project_name: str,
    zip_name: str,
    included_files: list[str],
    screenshot_source: str,
) -> str:
    branch = run_git(["rev-parse", "--abbrev-ref", "HEAD"])
    commit = run_git(["rev-parse", "HEAD"])
    remote = run_git(["config", "--get", "remote.origin.url"])
    generated_at = datetime.now(timezone.utc).isoformat()

    file_list = "\n".join(f"- `{path}`" for path in sorted(included_files))
    if not file_list:
        file_list = "- No visual files were included."

    return f"""# Visual Package Manifest

Project name: {project_name}
Generated timestamp: {generated_at}
Git branch: {branch}
Git commit hash: {commit}
Repository remote URL: {remote}
ZIP file name: {zip_name}
ZIP SHA256: computed after archive creation and printed by `scripts/build_visual_package.py`.

## Screenshot Source

{screenshot_source}

## Mockup Source

Mockups are deterministic source-based portfolio visuals generated by `scripts/generate_visual_assets.py` from the UsahaNaik product scope, implemented feature set, and visual direction.

## Campaign Visuals

- `linkedin_cover.png`
- `linkedin_square_post.png`
- `linkedin_carousel_01_intro.png`
- `linkedin_carousel_02_features.png`
- `linkedin_carousel_03_tech_stack.png`
- `linkedin_carousel_04_demo.png`
- `linkedin_carousel_05_closing.png`
- `linkedin_banner.png`

## Included Files

{file_list}

## Excluded Summary

The package intentionally excludes source code, `.git/`, dependency folders, build outputs, cache folders, previous archives, local environment files, and large model/checkpoint artifacts.

## App Run Status

The Android app was validated with Gradle build/test commands during packaging. Runtime screenshot capture requires an attached emulator or device.
"""


def main() -> int:
    project_dir = Path.cwd()
    project_name = project_dir.name
    dist_dir = project_dir / "dist"
    staging_dir = dist_dir / ".visual_package_staging"
    zip_name = f"{project_name}_LinkedIn_Visual_Package.zip"
    zip_path = dist_dir / zip_name

    dist_dir.mkdir(exist_ok=True)
    if staging_dir.exists():
        shutil.rmtree(staging_dir)
    staging_dir.mkdir(parents=True)

    screenshots_out = staging_dir / "screenshots"
    mockups_out = staging_dir / "mockups"
    linkedin_out = staging_dir / "linkedin_campaign"
    screenshots_out.mkdir()
    mockups_out.mkdir()
    linkedin_out.mkdir()

    included: list[str] = []
    included.extend(copy_tree_contents(project_dir, SCREENSHOT_DIR, screenshots_out))
    included.extend(copy_tree_contents(project_dir, MOCKUP_DIR, mockups_out))
    included.extend(copy_tree_contents(project_dir, LINKEDIN_DIR, linkedin_out))

    screenshot_pngs = list((project_dir / SCREENSHOT_DIR).glob("*.png")) if (project_dir / SCREENSHOT_DIR).exists() else []
    if screenshot_pngs:
        screenshot_source = "Runtime screenshots are included from `docs/evidence/screenshots/final/`."
    else:
        screenshot_source = (
            "No runtime screenshots were captured during packaging because no Android emulator/device was attached. "
            "The screenshots folder includes a manual capture guide."
        )

    readme = build_readme(project_name, screenshot_source)
    manifest = build_manifest(project_name, zip_name, included, screenshot_source)
    (staging_dir / "VISUAL_PACKAGE_README.md").write_text(readme, encoding="utf-8")
    (staging_dir / "VISUAL_PACKAGE_MANIFEST.md").write_text(manifest, encoding="utf-8")
    included.extend(["VISUAL_PACKAGE_README.md", "VISUAL_PACKAGE_MANIFEST.md"])

    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for file_path in sorted(staging_dir.rglob("*")):
            if file_path.is_file():
                archive.write(file_path, file_path.relative_to(staging_dir))

    size_bytes = zip_path.stat().st_size
    zip_hash = sha256_file(zip_path)
    shutil.rmtree(staging_dir)

    print(f"Project name: {project_name}")
    print(f"Output ZIP path: {zip_path}")
    print(f"ZIP size: {size_bytes} bytes")
    print(f"Included file count: {len(included)}")
    print("Excluded pattern summary: source code, Git data, dependency folders, build outputs, archives, caches, local env files, and model artifacts")
    print(f"SHA256: {zip_hash}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
